import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from 'next/font/google';
import Footer from "@/componentes/Footer/Footer";
import Header from "@/componentes/Header/Header";
import { Toaster } from "sonner";

const montserrat = Montserrat({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "Gerenciador de Filmes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
      <Header />
        {children}
      <Footer />  
      <Toaster
        position="top-right"
        richColors
      />
      </body>
    </html>
  );
}